spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lessayer_v2_backend
    username: zkhuang
    password: "!Ohmygod123"
    ## Remove hikari parameters if is still under development
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
        